### ISSUE TITLE
Chat is broken in 267

### ISSUE THREAD

**Issue by tttppp** [zond/android-diplicity#75]
Build 267 seems to have no chat. I tried a few games which I'm in or not in, and the app crashes when trying to view chat.

**Comment by tttppp** [comment]
Chat notifications still work.

**Comment by zond** [comment]
Weird, it works for me :O

What's the stack trace?

**Comment by tttppp** [comment]
{code}
04-09 18:46:35.084 12715-12715/? E/UncaughtException: java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
                                                          at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:114)
                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                          at android.os.Looper.loop(Looper.java:158)
                                                          at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                       Caused by: java.lang.NoSuchMethodError: No virtual method sort(Ljava/util/Comparator;)V in class Ljava/util/ArrayList; or its super classes (declaration of 'java.util.ArrayList' appears in /system/framework/core-libart.jar)
                                                          at se.oort.diplicity.game.PressActivity$3.send(PressActivity.java:193)
                                                          at se.oort.diplicity.game.PressActivity$3.send(PressActivity.java:188)
                                                          at se.oort.diplicity.RetrofitActivity$2.onNext(RetrofitActivity.java:285)
                                                          at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
                                                          at rx.internal.operators.OperatorSubscribeOn$1$1.onNext(OperatorSubscribeOn.java:53)
                                                          at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:227)
                                                          at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107)
                                                          at android.os.Handler.handleCallback(Handler.java:739) 
                                                          at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                          at android.os.Looper.loop(Looper.java:158) 
                                                          at android.app.ActivityThread.main(ActivityThread.java:7224) 
                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
04-09 18:46:35.354 12715-12715/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: se.oort.diplicity, PID: 12715
                                                   java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
                                                       at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:114)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:158)
                                                       at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                    Caused by: java.lang.NoSuchMethodError: No virtual method sort(Ljava/util/Comparator;)V in class Ljava/util/ArrayList; or its super classes (declaration of 'java.util.ArrayList' appears in /system/framework/core-libart.jar)
                                                       at se.oort.diplicity.game.PressActivity$3.send(PressActivity.java:193)
                                                       at se.oort.diplicity.game.PressActivity$3.send(PressActivity.java:188)
                                                       at se.oort.diplicity.RetrofitActivity$2.onNext(RetrofitActivity.java:285)
                                                       at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
                                                       at rx.internal.operators.OperatorSubscribeOn$1$1.onNext(OperatorSubscribeOn.java:53)
                                                       at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:227)
                                                       at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107)
                                                       at android.os.Handler.handleCallback(Handler.java:739) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                       at android.os.Looper.loop(Looper.java:158) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:7224) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
{code}

**Comment by zond** [comment]
Ah.

https://stackoverflow.com/questions/38951218/java-lang-nosuchmethoderror-no-interface-method-sortljava-util-comparator-ex

Pushing a new version.

**Comment by zond** [comment]
Aand a new version rolled out.

Tell me if it helped :)

**Comment by zond** [comment]
Great :)

Yeah, phase transitions in chat logs was one of the things I missed from Droidippy.
